[package]
name = "feedbin_cleaner"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1.0"
chrono = "0.4"
base64 = "0.13"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
structopt = "0.3"